# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Tag + Release

on:
  push:
    tags:
      - v*

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create env file
      env:
        DB_NAME: ${{secrets.DB_NAME}}
        DB_HOST: ${{secrets.DB_HOST}}
        DB_USER: ${{secrets.DB_USER}}
        DB_PASS: ${{secrets.DB_PASS}}
      run: |
        touch ./src/main/resources/env.properties
        echo DB_HOST="$DB_HOST" >> ./src/main/resources/env.properties
        echo DB_NAME="$DB_NAME" >> ./src/main/resources/env.properties
        echo DB_USER="$DB_USER" >> ./src/main/resources/env.properties
        echo DB_PASS="$DB_PASS" >> ./src/main/resources/env.properties
        cat ./src/main/resources/env.properties
      shell: bash
    - name: Set up JDK 17
      uses: actions/setup-java@v3.0.0
      with:
        java-version: '17.0.2'
        distribution: 'zulu'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: build
    - uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: build/libs/FevEventBackend-${{github.ref_name}}.jar